name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"
rev = "v4.23.0"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[require]]
name = "lean-semver"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.23.0"

# run via 
# cd docbuild
# DOCGEN_SRC="github" lake build SemVer:docs
