name = "lean-semver"
version = "1.0.1"
defaultTargets = ["lean-semver", "tests"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "SemVer"
path = "SemVer"

[[lean_exe]]
name = "tests"
root = "Tests"

[[lean_exe]]
name = "lean-semver"
root = "Main"
