name = "lean-semver"
version = "0.7.0"
defaultTargets = ["lean-semver"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[lean_lib]]
name = "SemVer"

[[lean_exe]]
name = "lean-semver"
root = "Main"
